export const pandocFormatsSharedText = [
  "biblatex",
  "bibtex",
  "commonmark",
  "commonmark_x",
  "csljson",
  "docbook",
  "docbook4",
  "docbook5",
  "dokuwiki",
  "gfm",
  "haddock",
  "html",
  "ipynb",
  "jats",
  "jira",
  "json",
  "latex",
  "man",
  "markdown",
  "markdown_github",
  "markdown_mmd",
  "markdown_phpextra",
  "markdown_strict",
  "mediawiki",
  "ms",
  "muse",
  "native",
  "opendocument",
  "opml",
  "org",
  "rst",
  "rtf",
  "textile",
] as const

export type PandocFormatSharedText = (typeof pandocFormatsSharedText)[number]
