import { pandocOutputFormats } from "@client/pandocFormatsOutput"

export const plainTextFormatsSet = new Set([
  "ansi",
  "asciidoc",
  "asciidoc_legacy",
  "asciidoctor",
  "bbcode",
  "bbcode_fluxbb",
  "bbcode_hubzilla",
  "bbcode_phpbb",
  "bbcode_steam",
  "bbcode_xenforo",
  "biblatex",
  "bibtex",
  "commonmark",
  "commonmark_x",
  "csljson",
  "djot",
  "docbook",
  "docbook4",
  "docbook5",
  "dokuwiki",
  "gfm",
  "haddock",
  "html",
  "html4",
  "html5",
  "ipynb",
  "jats",
  "jats_archiving",
  "jats_articleauthoring",
  "jats_publishing",
  "jira",
  "json",
  "latex",
  "man",
  "markdown",
  "markdown_github",
  "markdown_mmd",
  "markdown_phpextra",
  "markdown_strict",
  "markua",
  "mediawiki",
  "ms",
  "muse",
  "native",
  "opendocument",
  "org",
  "rst",
  "rtf",
  "tei",
  "texinfo",
  "textile",
  "vimdoc",
  "xml",
  "xwiki",
  "zimwiki",
])

export const plainTextFormats = [...plainTextFormatsSet] as const

export const binaryFormats = pandocOutputFormats.filter(
  (f) => !plainTextFormatsSet.has(f),
) as readonly string[]

export const pandocFormatIsText = (format: string): boolean => plainTextFormatsSet.has(format)
